name: lifestylescreening
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.3
  firebase_core: ^0.5.3
  #flutter_switch: ^0.0.2
  firebase_auth: ^0.18.4+1
  image_picker: ^0.6.7+17
  permission_handler: ^5.0.1+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  hovering: ^1.0.2
  uuid: 2.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.8.1
  rename: ^1.2.0
  mockito: ^4.1.3


flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logo_large.png"
  image_path_ios: "assets/images/logo_large.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/images/logo_white.jpg" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/images/logo_large.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
   - family: Sofia
     fonts:
       - asset: assets/fonts/Sofia-Pro-Black-Az.ttf
       - asset: assets/fonts/Sofia-Pro-Bold-Az.ttf
       - asset: assets/fonts/Sofia-Pro-Light-Az.ttf
       - asset: assets/fonts/Sofia-Pro-Medium-Az.ttf
       - asset: assets/fonts/Sofia-Pro-Regular-Az.ttf
       - asset: assets/fonts/Sofia-Pro-UltraLight-Az.ttf
   - family:  HealthpointIcons
     fonts:
      - asset: assets/icon/HealthpointIcons.ttf
  assets: 
  - assets/images/
  - playstore.png
  - health.png
  - settings-info.png
  uses-material-design: true
